### PR TITLE
enable jupyterlab-s3-browser extension for browsing s3 storage

### PR DESCRIPTION
**Pull request by harshad16**
enable jupyterlab-s3-browser extension for browsing s3 storage
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

# Related Issues and Dependencies

Related-to: https://github.com/thoth-station/s2i-generic-data-science-notebook/issues/15

# Description
set the jupyterlab s3 browser extension.
Reference: https://github.com/IBM/jupyterlab-s3-browser#jupyterlab-3

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
lgtm!! Can you add the extension to the README please?

**Review by pacospace — APPROVED** [review]
lgtm! 💯

**Comment by MichaelClifford** [comment]
@pacospace @harshad16 Is there documentation for how to get this to work on Opf? Launching a v8 JL does not appear to have this feature.

**Comment by harshad16** [comment]
> Is there documentation for how to get this to work on Opf? Launching a v8 JL does not appear to have this feature.

This would get to operate-first, when the newer odh is released.
operate-first would like to rely on odh, as it is just running an instance, and not maintaining the project.
this is what I have know, I don't know what and where to document.

**Pull request merged**
