### PR TITLE
Introduce jupyterlab-git extension

### LINKED ISSUE #1: Consistent method for connecting nb servers to github repos
**Is your feature request related to a problem? Please describe.**
As a DS user, I need to connect my NB server to a GitHub repo so I can pull files from or push files to an existing repo that I use for my data science project.

**Describe the solution you'd like**
Ideally, we have a simple way that will give us the desired functionality built-in to our notebook servers so that we can give a consistent user experience.

**Describe alternatives you've considered**
We have other images that utilize Elyra.  If it's possible to backport the solution there, that might be a win, but we are open to ideas.

**Additional context**

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

# Related Issues and Dependencies

Fixes: https://github.com/thoth-station/s2i-generic-data-science-notebook/issues/1

# Description

Add jupyterlab-git extension compatible with Jupyterlab >=3.*

### CODE REVIEW

**Comment by harshad16** [comment]
@pacospace these changes are already present in the repository.

**Comment by pacospace** [comment]
> @pacospace these changes are already present in the repository.

Actually, the jupyterlab-git extension compatible with jupyterlab3 in version v0.0.1 is missing: https://github.com/thoth-station/s2i-generic-data-science-notebook/blob/4378a93c814a58e78286f325eb7c074c2d06bb01/Pipfile.lock#L463, it should be : https://pypi.org/project/jupyterlab-git/0.30.0b2/

**Comment by pacospace** [comment]
> @pacospace these changes are already present in the repository.

Ref: https://github.com/thoth-station/s2i-generic-data-science-notebook/issues/1#issuecomment-810304264

**Review by harshad16 — APPROVED** [review]
thank you for this

**Pull request merged**
